// Code generated by tools/generate.py from cexy-api-spec; DO NOT EDIT.

package cexy

import (
	"encoding/json"
	"time"
)

// AccountId: The id of the account a credential belongs to, and nothing else.
type AccountId struct {
	// Account id: the same hex as the realtime `authenticated` reply's `user_id`.
	UserID string `json:"user_id"`
}

// APIKey: An existing key. Never carries the secret.
type APIKey struct {
	// Permitted source addresses. Empty means unrestricted.
	AllowedIPs []string `json:"allowed_ips"`
	// When it was created.
	CreatedAt time.Time `json:"created_at"`
	// When it stops working.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Opaque key identifier, used to revoke it.
	ID string `json:"id"`
	// The public key id, sent as `X-API-Key`.
	KeyID string `json:"key_id"`
	// Human label.
	Label string `json:"label"`
	// When it was last used, if ever.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// Whether it has been revoked.
	Revoked bool `json:"revoked"`
	// Granted scopes.
	Scopes []APIScope `json:"scopes"`
}

// APIScope: Scope attached to an API key.
//
// Scopes narrow what an API key may do. They apply to API keys only: a signed-in session carries none and is not limited by them.
//
// The type is open: values added to the API later decode without error.
type APIScope string

const (
	APIScopeRead  APIScope = "read"
	APIScopeTrade APIScope = "trade"
)

// AssetNetwork: An asset's policy on one network.
type AssetNetwork struct {
	// Contract address or chain asset id, for a token.
	ContractAddress *string `json:"contract_address,omitempty"`
	// Confirmations before a deposit is credited.
	DepositConfirmations int `json:"deposit_confirmations"`
	// Whether deposits are accepted.
	DepositEnabled bool              `json:"deposit_enabled"`
	Maintenance    *MaintenanceState `json:"maintenance,omitempty"`
	MaxWithdrawal  *Amount           `json:"max_withdrawal,omitempty"`
	// What to call the memo field in a UI.
	MemoLabel *string `json:"memo_label,omitempty"`
	// Whether a memo is mandatory.
	MemoRequired bool `json:"memo_required"`
	// Whether the network uses a memo / destination tag.
	MemoSupported bool   `json:"memo_supported"`
	MinDeposit    Amount `json:"min_deposit"`
	MinWithdrawal Amount `json:"min_withdrawal"`
	// Network code.
	Network string `json:"network"`
	// Network display name.
	NetworkName string `json:"network_name"`
	// Operator note.
	Notice *string `json:"notice,omitempty"`
	// How the asset exists on this chain.
	TokenKind string `json:"token_kind"`
	// Decimal places a withdrawal amount is truncated to.
	WithdrawalDecimals int `json:"withdrawal_decimals"`
	// Whether withdrawals are accepted.
	WithdrawalEnabled bool   `json:"withdrawal_enabled"`
	WithdrawalFee     Amount `json:"withdrawal_fee"`
	// Asset the withdrawal fee is charged in.
	WithdrawalFeeAsset string `json:"withdrawal_fee_asset"`
}

// Asset: A tradable asset.
type Asset struct {
	// Accounting precision: the decimal places the exchange records internally.
	//
	// Use this for arithmetic. For rendering, use `display_decimals`.
	Decimals int `json:"decimals"`
	// Decimal places to show in a user interface.
	//
	// Always less than or equal to `decimals`. Rounding for display is presentation only and must never be fed back into a request.
	DisplayDecimals int `json:"display_decimals"`
	// Identifier for a client-bundled icon, when no logo URL is set.
	IconKey *string `json:"icon_key,omitempty"`
	// Logo URL, when the operator has configured one.
	LogoURL *string `json:"logo_url,omitempty"`
	// How old this asset's price may be before it is refused, in seconds.
	//
	// The global default unless an operator set an override for this asset. Exposed beside the flag because the flag alone cannot explain itself: an asset that is not stale after a week and one that is not stale after an hour look identical without it.
	MaxPriceAgeSecs int64 `json:"max_price_age_secs"`
	// Display name.
	Name string `json:"name"`
	// Networks this asset can be deposited to or withdrawn from.
	Networks []AssetNetwork `json:"networks"`
	// Operator note, e.g. why deposits are paused.
	Notice *string `json:"notice,omitempty"`
	// Uppercase ticker.
	Symbol string `json:"symbol"`
	// Whether the asset may appear in markets.
	TradingEnabled bool   `json:"trading_enabled"`
	UsdPrice       Amount `json:"usd_price"`
	// Whether that price is too old to compute with.
	//
	// When true, the exchange refuses to derive anything from it: daily limits and auto-approval fail closed rather than guess, and a stored USD value is recorded as absent rather than as a confident wrong figure.
	UsdPriceStale bool `json:"usd_price_stale"`
	// When that price was last set.
	//
	// Exposed because the price is typed in by an operator and refreshed by nothing — there is no feed. Without the timestamp a caller cannot tell a price set an hour ago from one set last month, and both look equally authoritative.
	UsdPriceUpdatedAt time.Time `json:"usd_price_updated_at"`
	// Project website.
	WebsiteURL *string `json:"website_url,omitempty"`
}

// Balance: A balance in one asset.
type Balance struct {
	// Asset symbol.
	Asset     string `json:"asset"`
	Available Amount `json:"available"`
	// Internal transfers to this account still held, soonest released first; empty when none. Their sum is part of `locked`. Shows at most 100.
	HeldIncoming []HeldIncoming `json:"held_incoming"`
	Locked       Amount         `json:"locked"`
	Pending      Amount         `json:"pending"`
	// This balance's sequence: it rises with every change to it, and `balance.updated` carries the same number as `data.sequence`. Apply an event only if its sequence is greater than the one this snapshot holds. 0 for a balance never touched.
	Sequence int64  `json:"sequence"`
	Total    Amount `json:"total"`
}

// CancelAllAfterRequest: Arms, re-arms or disarms the dead-man switch.
type CancelAllAfterRequest struct {
	// One market's orders only. Omitted or `null`, the switch covers every market; an empty string is refused (400). A per-market switch and the all-markets switch are separate: each fires on its own.
	Symbol *string `json:"symbol,omitempty"`
	// Milliseconds from now after which the open orders in scope are cancelled, unless the switch is armed again first: from 5000 to 600000. `0` disarms.
	TimeoutMs int64 `json:"timeout_ms"`
}

// CancelAllAfter: The dead-man switch, as just set.
type CancelAllAfter struct {
	// Whether a deadline is now armed for this scope. `false` after a disarm.
	Armed bool `json:"armed"`
	// When the orders are cancelled unless armed again. `null` when disarmed.
	Deadline *time.Time `json:"deadline,omitempty"`
	// The server's time after the deadline was stored, to measure the deadline against.
	ServerTime time.Time `json:"server_time"`
	// The market it covers, or `null` for every market.
	Symbol *string `json:"symbol,omitempty"`
	// The timeout asked for, in milliseconds.
	TimeoutMs int64 `json:"timeout_ms"`
}

// CancelAllRequest: Cancels every open order, optionally within one market.
type CancelAllRequest struct {
	// Limit the cancellation to one market. Omitted or `null`, every market's open orders are cancelled.
	Symbol *string `json:"symbol,omitempty"`
}

// CancelAllResult: What a bulk cancellation achieved.
//
// Every order the call handled is in exactly one of `cancelled`, `already_closed` and `failed`.
type CancelAllResult struct {
	// Orders that closed on their own (filled, rejected, cancelled elsewhere) before this call reached them. Nothing was done to them, and they are not failures.
	AlreadyClosed []string `json:"already_closed"`
	// Orders cancelled.
	Cancelled []string `json:"cancelled"`
	// Orders that could not be cancelled in this call. Check `failures` for why, then refresh or call again.
	Failed []string `json:"failed"`
	// Why each order in `failed` could not be cancelled.
	Failures []CancelFailure `json:"failures"`
	// More open orders exist than one call handles (500). Call again.
	HasMore bool `json:"has_more"`
}

// CancelFailure: Why one order could not be cancelled.
type CancelFailure struct {
	// The error code of the attempt, as in any error response: e.g. `INVALID_STATE` for an order still being placed when the wait ran out, or `MARKET_UNAVAILABLE`.
	Code string `json:"code"`
	// Its message.
	Message string `json:"message"`
	// The order.
	OrderID string `json:"order_id"`
}

// FuturesCandle: One candle.
type FuturesCandle struct {
	Close Amount `json:"close"`
	// Close time, unix milliseconds.
	CloseTime int64  `json:"close_time"`
	High      Amount `json:"high"`
	Low       Amount `json:"low"`
	Open      Amount `json:"open"`
	// Open time, unix milliseconds.
	OpenTime int64 `json:"open_time"`
	// Number of trades.
	Trades int64  `json:"trades"`
	Volume Amount `json:"volume"`
}

// CandleInterval: Candle/kline intervals for market data.
//
// The type is open: values added to the API later decode without error.
type CandleInterval string

const (
	CandleInterval1m  CandleInterval = "1m"
	CandleInterval5m  CandleInterval = "5m"
	CandleInterval15m CandleInterval = "15m"
	CandleInterval30m CandleInterval = "30m"
	CandleInterval1h  CandleInterval = "1h"
	CandleInterval4h  CandleInterval = "4h"
	CandleInterval1d  CandleInterval = "1d"
	CandleInterval1w  CandleInterval = "1w"
)

// Candle: An OHLCV bucket.
type Candle struct {
	Close Amount `json:"close"`
	High  Amount `json:"high"`
	Low   Amount `json:"low"`
	Open  Amount `json:"open"`
	// Bucket start.
	OpenTime    time.Time `json:"open_time"`
	QuoteVolume Amount    `json:"quote_volume"`
	// Number of trades.
	TradeCount int64  `json:"trade_count"`
	Volume     Amount `json:"volume"`
}

// DepositAddress: A deposit address.
type DepositAddress struct {
	// The address to send to.
	Address string `json:"address"`
	// Asset symbol.
	Asset string `json:"asset"`
	// When the address was issued.
	CreatedAt time.Time `json:"created_at"`
	// Confirmations before the deposit is credited.
	DepositConfirmations int `json:"deposit_confirmations"`
	// Memo / destination tag. **Required when present** — a deposit without it may be unrecoverable.
	Memo *string `json:"memo,omitempty"`
	// What to call the memo field in a UI.
	MemoLabel  *string `json:"memo_label,omitempty"`
	MinDeposit Amount  `json:"min_deposit"`
	// Network code.
	Network string `json:"network"`
}

// DepositID: Unique identifier of a deposit.
//
// An alias of string: its format is not checked, so a future format keeps working.
type DepositID = string

// Deposit: A deposit.
type Deposit struct {
	// Address that received it.
	Address string `json:"address"`
	Amount  Amount `json:"amount"`
	// Asset symbol.
	Asset string `json:"asset"`
	// Confirmations observed.
	Confirmations int `json:"confirmations"`
	// When it was credited.
	CreditedAt *time.Time `json:"credited_at,omitempty"`
	// Explorer link, when the network has one configured.
	ExplorerURL *string `json:"explorer_url,omitempty"`
	// When it was first observed.
	FirstSeenAt time.Time `json:"first_seen_at"`
	// Deposit id.
	ID string `json:"id"`
	// Memo, if any.
	Memo *string `json:"memo,omitempty"`
	// Network code.
	Network string `json:"network"`
	// Operator note, e.g. why it was reversed.
	Note *string `json:"note,omitempty"`
	// Position within the transaction. Distinguishes two outputs of one transaction.
	OutputIndex int `json:"output_index"`
	// Confirmations required to credit.
	RequiredConfirmations int           `json:"required_confirmations"`
	Status                DepositStatus `json:"status"`
	// Transaction hash.
	Txid string `json:"txid"`
}

// DepositStatus: Lifecycle of an incoming blockchain deposit.
//
// The type is open: values added to the API later decode without error.
type DepositStatus string

const (
	DepositStatusDetected     DepositStatus = "detected"
	DepositStatusCredited     DepositStatus = "credited"
	DepositStatusReversed     DepositStatus = "reversed"
	DepositStatusOrphaned     DepositStatus = "orphaned"
	DepositStatusBelowMinimum DepositStatus = "below_minimum"
	DepositStatusUnderReview  DepositStatus = "under_review"
	DepositStatusInternal     DepositStatus = "internal"
)

// ExchangeConfig: Public exchange configuration.
//
// Everything a frontend needs to render itself without a deploy: branding, limits, supported intervals, and whether the exchange is in maintenance.
type ExchangeConfig struct {
	// Candle intervals the API serves.
	CandleIntervals []CandleInterval `json:"candle_intervals"`
	// Default page size for paginated endpoints.
	DefaultPageSize int `json:"default_page_size"`
	// Whether registration verifies the email address with an emailed code before the authenticator step. Lets a signup form show the right number of steps up front.
	EmailVerificationRequired bool `json:"email_verification_required"`
	// Feature flags a frontend may use to hide unavailable functionality.
	//
	// Presentation only. The backend enforces every rule independently.
	Features map[string]bool `json:"features"`
	// Message to show while in maintenance.
	MaintenanceMessage *string `json:"maintenance_message,omitempty"`
	// Whether the exchange is in maintenance mode.
	MaintenanceMode bool `json:"maintenance_mode"`
	// Maximum page size.
	MaxPageSize int `json:"max_page_size"`
	// Display name.
	Name          string        `json:"name"`
	PasswordRules PasswordRules `json:"password_rules"`
	// Whether new registrations are accepted.
	RegistrationEnabled bool `json:"registration_enabled"`
	// Support contact.
	SupportURL *string `json:"support_url,omitempty"`
	// Seconds a verified two-factor code authorises sensitive actions for.
	TwoFactorFreshnessSeconds int64 `json:"two_factor_freshness_seconds"`
	// Where to open the realtime connection, relative to this API's origin.
	WebsocketPath string `json:"websocket_path"`
	// The realtime protocol version this server speaks.
	WebsocketProtocolVersion int `json:"websocket_protocol_version"`
}

// ExitPoolRequest: Removes liquidity from a pool.
type ExitPoolRequest struct {
	Shares Amount `json:"shares"`
}

// ExitPoolResult: What an exit produced.
type ExitPoolResult struct {
	BaseReturned  Amount `json:"base_returned"`
	QuoteReturned Amount `json:"quote_returned"`
	SharesBurned  Amount `json:"shares_burned"`
	SharesHeld    Amount `json:"shares_held"`
}

// FeeSchedule: A fee tier.
type FeeSchedule struct {
	// Human label.
	Label string `json:"label"`
	// Maker rate, as a percentage.
	MakerFeePercent string `json:"maker_fee_percent"`
	Min30dVolumeUsd Amount `json:"min_30d_volume_usd"`
	// Taker rate, as a percentage.
	TakerFeePercent string `json:"taker_fee_percent"`
	// Tier index.
	Tier int `json:"tier"`
}

// FuturesFill: One fill.
type FuturesFill struct {
	ClosedPnl Amount `json:"closed_pnl"`
	// Coin.
	Coin string `json:"coin"`
	// The provider's description of the fill's effect (`Open Long`, `Close Short`, ...).
	Direction string `json:"direction"`
	// Our id for it.
	ID string `json:"id"`
	// Our id for its order.
	OrderID string `json:"order_id"`
	Price   Amount `json:"price"`
	// `buy` or `sell`.
	Side string `json:"side"`
	Size Amount `json:"size"`
	// Whether this fill took liquidity.
	Taker bool `json:"taker"`
	// When, unix milliseconds.
	Time int64 `json:"time"`
}

// Fill: One of the caller's executions.
type Fill struct {
	Fee Amount `json:"fee"`
	// Asset the fee was charged in.
	FeeAsset string `json:"fee_asset"`
	// The caller's order.
	OrderID       string        `json:"order_id"`
	Price         Amount        `json:"price"`
	Quantity      Amount        `json:"quantity"`
	QuoteQuantity Amount        `json:"quote_quantity"`
	Role          LiquidityRole `json:"role"`
	Side          OrderSide     `json:"side"`
	// Market symbol.
	Symbol string `json:"symbol"`
	// When it executed.
	Timestamp time.Time `json:"timestamp"`
	// Trade id.
	TradeID string `json:"trade_id"`
}

// Funding: One funding payment.
type Funding struct {
	Amount Amount `json:"amount"`
	// Coin.
	Coin         string `json:"coin"`
	PositionSize Amount `json:"position_size"`
	Rate         Amount `json:"rate"`
	// When, unix milliseconds.
	Time int64 `json:"time"`
}

// FuturesBook: A futures market's book.
type FuturesBook struct {
	// When the provider last sent it.
	AsOf time.Time `json:"as_of"`
	// Asks, best first.
	Asks []Level `json:"asks"`
	// Bids, best first.
	Bids []Level `json:"bids"`
	// Coin.
	Coin string `json:"coin"`
	// The live feed is not healthy: the book may be out of date.
	Stale bool `json:"stale"`
}

// FuturesCandles: A futures market's candles.
type FuturesCandles struct {
	// When read.
	AsOf time.Time `json:"as_of"`
	// Candles, oldest first.
	Candles []FuturesCandle `json:"candles"`
	// Coin.
	Coin string `json:"coin"`
	// Interval.
	Interval string `json:"interval"`
	// Older than it should be.
	Stale bool `json:"stale"`
}

// FuturesFills: A page of the account's fills.
type FuturesFills struct {
	// Newest first; fills sharing a millisecond in a fixed order. A page may be short of 100 and still be followed by more.
	Fills []FuturesFill `json:"fills"`
	// Whether the account has a futures account.
	HasAccount bool `json:"has_account"`
	// Pass as `cursor` for older fills, exactly as given; `null` at the end (30 days back). Opaque: it may carry more than a time.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// FuturesFunding: A page of the account's funding payments.
type FuturesFunding struct {
	// Newest first.
	Funding []Funding `json:"funding"`
	// Whether the account has a futures account.
	HasAccount bool `json:"has_account"`
	// Pass as `cursor` for older payments, exactly as given; `null` at the end (30 days back). Opaque.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// FuturesMarket: One futures market.
type FuturesMarket struct {
	// When this data was read.
	AsOf   time.Time  `json:"as_of"`
	Market PerpMarket `json:"market"`
	// Older than it should be.
	Stale bool `json:"stale"`
}

// FuturesMarkets: Every listed futures market.
type FuturesMarkets struct {
	// When this data was read from the futures provider.
	AsOf time.Time `json:"as_of"`
	// The markets, in the provider's order. Delisted markets are not included.
	Markets []PerpMarket `json:"markets"`
	// The data is older than it should be: the provider could not be read just now.
	Stale bool `json:"stale"`
}

// FuturesOpenOrders: The account's open orders.
type FuturesOpenOrders struct {
	// When read.
	AsOf *time.Time `json:"as_of,omitempty"`
	// Whether the account has a futures account.
	HasAccount bool `json:"has_account"`
	// The open orders.
	Orders []OpenOrder `json:"orders"`
	// Older than it should be.
	Stale bool `json:"stale"`
}

// FuturesPositions: The account's positions.
type FuturesPositions struct {
	// When read.
	AsOf *time.Time `json:"as_of,omitempty"`
	// Whether the account has a futures account. Without one, nothing else is meaningful.
	HasAccount bool       `json:"has_account"`
	Positions  *Positions `json:"positions,omitempty"`
	// Older than it should be.
	Stale bool `json:"stale"`
}

// FuturesTrades: A futures market's recent public trades.
type FuturesTrades struct {
	// Coin.
	Coin string `json:"coin"`
	// The live feed is not healthy, or was only just opened: trades may be missing.
	Stale bool `json:"stale"`
	// Newest first.
	Trades []FuturesPublicTrade `json:"trades"`
}

// FuturesTransferID: Unique identifier of a futures collateral transfer.
//
// An alias of string: its format is not checked, so a future format keeps working.
type FuturesTransferID = string

// HeldIncoming: An internal transfer credited to `locked` and not yet available.
type HeldIncoming struct {
	Amount Amount `json:"amount"`
	// When it becomes available, unless an operator cancels it before then.
	AvailableAt time.Time `json:"available_at"`
	// The transfer.
	TransferID string `json:"transfer_id"`
}

// JoinPoolRequest: Adds liquidity to a pool.
type JoinPoolRequest struct {
	BaseAmount               Amount  `json:"base_amount"`
	MaxRatioDeviationPercent *Amount `json:"max_ratio_deviation_percent,omitempty"`
	QuoteAmount              Amount  `json:"quote_amount"`
}

// JoinPoolResult: What a join produced.
type JoinPoolResult struct {
	BaseDeposited  Amount `json:"base_deposited"`
	QuoteDeposited Amount `json:"quote_deposited"`
	SharesHeld     Amount `json:"shares_held"`
	SharesMinted   Amount `json:"shares_minted"`
}

// LedgerEntryKind: What a ledger entry records.
//
// The type is open: values added to the API later decode without error.
type LedgerEntryKind string

const (
	LedgerEntryKindDeposit                   LedgerEntryKind = "deposit"
	LedgerEntryKindDepositReversal           LedgerEntryKind = "deposit_reversal"
	LedgerEntryKindWithdrawalDebit           LedgerEntryKind = "withdrawal_debit"
	LedgerEntryKindWithdrawalFee             LedgerEntryKind = "withdrawal_fee"
	LedgerEntryKindWithdrawalFeeReserve      LedgerEntryKind = "withdrawal_fee_reserve"
	LedgerEntryKindWithdrawalRelease         LedgerEntryKind = "withdrawal_release"
	LedgerEntryKindWithdrawalFeeRelease      LedgerEntryKind = "withdrawal_fee_release"
	LedgerEntryKindOrderReserve              LedgerEntryKind = "order_reserve"
	LedgerEntryKindWithdrawalReserve         LedgerEntryKind = "withdrawal_reserve"
	LedgerEntryKindOrderRelease              LedgerEntryKind = "order_release"
	LedgerEntryKindTradeDebit                LedgerEntryKind = "trade_debit"
	LedgerEntryKindTradeCredit               LedgerEntryKind = "trade_credit"
	LedgerEntryKindTradeFee                  LedgerEntryKind = "trade_fee"
	LedgerEntryKindTransferOut               LedgerEntryKind = "transfer_out"
	LedgerEntryKindTransferIn                LedgerEntryKind = "transfer_in"
	LedgerEntryKindTransferInHeld            LedgerEntryKind = "transfer_in_held"
	LedgerEntryKindTransferRelease           LedgerEntryKind = "transfer_release"
	LedgerEntryKindTransferReversal          LedgerEntryKind = "transfer_reversal"
	LedgerEntryKindAdjustmentCredit          LedgerEntryKind = "adjustment_credit"
	LedgerEntryKindAdjustmentDebit           LedgerEntryKind = "adjustment_debit"
	LedgerEntryKindRebate                    LedgerEntryKind = "rebate"
	LedgerEntryKindPoolJoin                  LedgerEntryKind = "pool_join"
	LedgerEntryKindPoolExit                  LedgerEntryKind = "pool_exit"
	LedgerEntryKindFuturesTransferReserve    LedgerEntryKind = "futures_transfer_reserve"
	LedgerEntryKindFuturesTransferRelease    LedgerEntryKind = "futures_transfer_release"
	LedgerEntryKindFuturesCollateralSent     LedgerEntryKind = "futures_collateral_sent"
	LedgerEntryKindFuturesCollateralReturned LedgerEntryKind = "futures_collateral_returned"
	LedgerEntryKindWithdrawalRefund          LedgerEntryKind = "withdrawal_refund"
)

// LedgerEntry: One entry from the account's ledger.
type LedgerEntry struct {
	// Asset symbol.
	Asset          string `json:"asset"`
	AvailableAfter Amount `json:"available_after"`
	AvailableDelta Amount `json:"available_delta"`
	// When it was applied.
	CreatedAt time.Time `json:"created_at"`
	// Entry id.
	ID           string          `json:"id"`
	Kind         LedgerEntryKind `json:"kind"`
	LockedDelta  Amount          `json:"locked_delta"`
	PendingDelta Amount          `json:"pending_delta"`
	Reference    LedgerReference `json:"reference"`
	// Position in this account's history for this asset.
	Sequence int64 `json:"sequence"`
}

// LedgerReference: What caused a ledger entry: one kind of cause per variant, told apart by `type`.
//
// Type says which variant it is; only that variant's fields are set. A type added to
// the API later decodes without error: Type holds it and Raw the whole object.
type LedgerReference struct {
	Type LedgerReferenceType `json:"type"`
	// Short machine-readable cause.
	//
	// Set for type system.
	Cause *string `json:"cause,omitempty"`
	// Set for type transfer.
	CounterpartyUserID *UserID `json:"counterparty_user_id,omitempty"`
	// Set for type deposit.
	DepositID *DepositID `json:"deposit_id,omitempty"`
	// Set for type futures_transfer.
	FuturesTransferID *FuturesTransferID `json:"futures_transfer_id,omitempty"`
	// Set for type adjustment.
	OperatorUserID *UserID `json:"operator_user_id,omitempty"`
	// Set for type order, trade.
	OrderID *OrderID `json:"order_id,omitempty"`
	// Set for type pool.
	PoolID *PoolID `json:"pool_id,omitempty"`
	// Set for type trade.
	TradeID *TradeID `json:"trade_id,omitempty"`
	// Shared reference linking both halves.
	//
	// Set for type transfer.
	TransferRef *string `json:"transfer_ref,omitempty"`
	// Set for type withdrawal.
	WithdrawalID *WithdrawalID `json:"withdrawal_id,omitempty"`
	// Raw is the object as received (nil for values built in code).
	Raw json.RawMessage `json:"-"`
}

// LedgerReferenceType tells the variants of LedgerReference apart. The type is open.
type LedgerReferenceType string

const (
	// A blockchain deposit.
	LedgerReferenceTypeDeposit LedgerReferenceType = "deposit"
	// A withdrawal request.
	LedgerReferenceTypeWithdrawal LedgerReferenceType = "withdrawal"
	// An order reservation or release.
	LedgerReferenceTypeOrder LedgerReferenceType = "order"
	// A trade settlement.
	LedgerReferenceTypeTrade LedgerReferenceType = "trade"
	// An internal transfer between accounts.
	LedgerReferenceTypeTransfer LedgerReferenceType = "transfer"
	// A manual operator adjustment. Always accompanied by an audit event.
	LedgerReferenceTypeAdjustment LedgerReferenceType = "adjustment"
	// A liquidity pool join or exit.
	LedgerReferenceTypePool LedgerReferenceType = "pool"
	// A movement of collateral to or from a futures account.
	//
	// Every entry a transfer produces carries the same one, so the reservation, the release and the completion can be read back as one event — which is what an operator resolving an ambiguous transfer needs.
	LedgerReferenceTypeFuturesTransfer LedgerReferenceType = "futures_transfer"
	// A system-originated credit with no user counterparty (rebate, promotion).
	LedgerReferenceTypeSystem LedgerReferenceType = "system"
)

// Known reports whether Type is one this SDK version knows.
func (r LedgerReference) Known() bool {
	switch r.Type {
	case LedgerReferenceTypeDeposit, LedgerReferenceTypeWithdrawal, LedgerReferenceTypeOrder, LedgerReferenceTypeTrade, LedgerReferenceTypeTransfer, LedgerReferenceTypeAdjustment, LedgerReferenceTypePool, LedgerReferenceTypeFuturesTransfer, LedgerReferenceTypeSystem:
		return true
	}
	return false
}

// UnmarshalJSON keeps the raw object and never fails on an unknown variant.
func (r *LedgerReference) UnmarshalJSON(b []byte) error {
	type plain LedgerReference
	var p plain
	if err := json.Unmarshal(b, &p); err != nil {
		*r = LedgerReference{Raw: append(json.RawMessage(nil), b...)}
		return nil
	}
	*r = LedgerReference(p)
	r.Raw = append(json.RawMessage(nil), b...)
	return nil
}

// Level: One price level.
type Level struct {
	Price Amount `json:"price"`
	Size  Amount `json:"size"`
}

// LiquidityRole: Whether a fill added liquidity (maker) or removed it (taker).
//
// The type is open: values added to the API later decode without error.
type LiquidityRole string

const (
	LiquidityRoleMaker LiquidityRole = "maker"
	LiquidityRoleTaker LiquidityRole = "taker"
)

// MaintenanceReason: Machine-readable reasons a capability is unavailable.
//
// The type is open: values added to the API later decode without error.
type MaintenanceReason string

const (
	MaintenanceReasonExchangeMaintenance MaintenanceReason = "exchange_maintenance"
	MaintenanceReasonNetworkUnavailable  MaintenanceReason = "network_unavailable"
	MaintenanceReasonDepositsDisabled    MaintenanceReason = "deposits_disabled"
	MaintenanceReasonWithdrawalsDisabled MaintenanceReason = "withdrawals_disabled"
	MaintenanceReasonAssetUnavailable    MaintenanceReason = "asset_unavailable"
)

// MaintenanceState: Why a capability is currently unavailable.
type MaintenanceState struct {
	// Operator-supplied explanation, when there is one.
	Message *string           `json:"message,omitempty"`
	Reason  MaintenanceReason `json:"reason"`
}

// Market: A tradable market and its current ticker.
type Market struct {
	// Base asset symbol.
	BaseAsset        string `json:"base_asset"`
	BestAsk          Amount `json:"best_ask"`
	BestBid          Amount `json:"best_bid"`
	Change24hPercent Amount `json:"change_24h_percent"`
	High24h          Amount `json:"high_24h"`
	LastPrice        Amount `json:"last_price"`
	// Time of the most recent trade.
	LastTradeAt *time.Time `json:"last_trade_at,omitempty"`
	LotSize     Amount     `json:"lot_size"`
	Low24h      Amount     `json:"low_24h"`
	MaxQuantity *Amount    `json:"max_quantity,omitempty"`
	MinNotional Amount     `json:"min_notional"`
	MinQuantity Amount     `json:"min_quantity"`
	// Decimal places a price may carry.
	PriceDecimals int `json:"price_decimals"`
	// Decimal places a quantity may carry.
	QuantityDecimals int `json:"quantity_decimals"`
	// Quote asset symbol.
	QuoteAsset     string       `json:"quote_asset"`
	QuoteVolume24h Amount       `json:"quote_volume_24h"`
	Status         MarketStatus `json:"status"`
	// Order types this market accepts.
	SupportedOrderTypes []OrderType `json:"supported_order_types"`
	// Time-in-force options this market accepts.
	SupportedTimeInForce []TimeInForce `json:"supported_time_in_force"`
	// `BASE/QUOTE`.
	Symbol   string `json:"symbol"`
	TickSize Amount `json:"tick_size"`
	// When trading opens, for a market not yet live.
	TradingStartsAt *time.Time `json:"trading_starts_at,omitempty"`
	Volume24h       Amount     `json:"volume_24h"`
}

// MarketStatus: Trading availability of a market.
//
// The type is open: values added to the API later decode without error.
type MarketStatus string

const (
	MarketStatusActive     MarketStatus = "active"
	MarketStatusPaused     MarketStatus = "paused"
	MarketStatusSellOnly   MarketStatus = "sell_only"
	MarketStatusPreTrading MarketStatus = "pre_trading"
	MarketStatusDelisted   MarketStatus = "delisted"
)

// Network: A blockchain network.
type Network struct {
	// Typical seconds between blocks, for estimating confirmation time.
	AverageBlockSeconds int `json:"average_block_seconds"`
	// Stable code.
	Code string `json:"code"`
	// Whether deposits on this network are actually being detected.
	//
	// False means either half of the pipeline is down: the last scan pass failed — a refused block range, a rate limit, a node that answers but will not serve logs — or finality could not be established, so deposits are being held rather than credited.
	//
	// Deposits sent now will be credited late, whenever the chain recovers, rather than lost. This is the field a status page should use to say deposits are degraded; `reachable` only says the node replies, which it may well do while yielding nothing.
	DepositsOperational bool `json:"deposits_operational"`
	// Template for an address explorer link. `{address}` is substituted.
	ExplorerAddressURLTemplate *string `json:"explorer_address_url_template,omitempty"`
	// Template for a transaction explorer link. `{txid}` is substituted.
	//
	// Absent when the operator has configured none; render no link rather than guessing a URL.
	ExplorerTxURLTemplate *string `json:"explorer_tx_url_template,omitempty"`
	// Whether the network is operational.
	IsActive bool `json:"is_active"`
	// Display name.
	Name string `json:"name"`
	// Whether the node answers at all.
	//
	// Narrower than it sounds, and deliberately so: a reachable node can still be failing to yield deposits. Do not render this alone as "network up".
	Reachable bool `json:"reachable"`
}

// NotificationKind: What a notice is about.
//
// A closed enum so a client can render each kind deliberately — an icon, a colour, a link — rather than pattern-matching on prose that may be reworded.
//
// The type is open: values added to the API later decode without error.
type NotificationKind string

const (
	NotificationKindDepositDetected     NotificationKind = "deposit_detected"
	NotificationKindDepositCredited     NotificationKind = "deposit_credited"
	NotificationKindWithdrawalRequested NotificationKind = "withdrawal_requested"
	NotificationKindWithdrawalSent      NotificationKind = "withdrawal_sent"
	NotificationKindWithdrawalCompleted NotificationKind = "withdrawal_completed"
	NotificationKindWithdrawalFailed    NotificationKind = "withdrawal_failed"
	NotificationKindOrderFilled         NotificationKind = "order_filled"
	NotificationKindOrderClosed         NotificationKind = "order_closed"
	NotificationKindSecurity            NotificationKind = "security"
	NotificationKindListingDecision     NotificationKind = "listing_decision"
	NotificationKindAnnouncement        NotificationKind = "announcement"
)

// Notification: An in-app notice.
type Notification struct {
	// One or two sentences.
	Body string `json:"body"`
	// When it was created.
	CreatedAt time.Time `json:"created_at"`
	// Notice id.
	ID   string           `json:"id"`
	Kind NotificationKind `json:"kind"`
	// Whether it has been read.
	Read bool `json:"read"`
	// The referenced resource's opaque id, for linking.
	ResourceID *string `json:"resource_id,omitempty"`
	// What it refers to: `deposit`, `withdrawal`, `order`.
	ResourceType *string `json:"resource_type,omitempty"`
	// Short heading.
	Title string `json:"title"`
}

// OpenOrder: One open order.
type OpenOrder struct {
	// Coin.
	Coin string `json:"coin"`
	// Our id for it, stable across reads.
	ID string `json:"id"`
	// The order type as the provider names it (`Limit`, `Stop Market`, ...).
	OrderType    string `json:"order_type"`
	OriginalSize Amount `json:"original_size"`
	// When placed, unix milliseconds.
	PlacedAt int64  `json:"placed_at"`
	Price    Amount `json:"price"`
	// Whether it may only reduce a position.
	ReduceOnly bool `json:"reduce_only"`
	// `buy` or `sell`.
	Side         string  `json:"side"`
	Size         Amount  `json:"size"`
	TriggerPrice *Amount `json:"trigger_price,omitempty"`
}

// OrderBook: One side of the order book, aggregated by price.
type OrderBook struct {
	// Asks, best first.
	Asks [][]Amount `json:"asks"`
	// Bids, best first, as `[price, quantity]` pairs.
	Bids [][]Amount `json:"bids"`
	// The realtime sequence this snapshot is current as of.
	//
	// Each `orderbook.update` on the `orderbook:{symbol}` websocket channel carries both sides of the top 50 levels in full (`data.full` is always `true`) and replaces the previous state; there are no deltas to buffer. Ignore an update whose `sequence` is at or below the one you hold. A gap only means a book was missed: the next update replaces it whole.
	Sequence int64 `json:"sequence"`
	// Market symbol.
	Symbol string `json:"symbol"`
	// When this snapshot was taken.
	Timestamp time.Time `json:"timestamp"`
}

// OrderID: Unique identifier of an order.
//
// An alias of string: its format is not checked, so a future format keeps working.
type OrderID = string

// Order: An order.
type Order struct {
	AveragePrice *Amount `json:"average_price,omitempty"`
	// Your identifier, if you supplied one.
	ClientOrderID *string `json:"client_order_id,omitempty"`
	// When it reached a terminal state.
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// When it was placed.
	CreatedAt time.Time `json:"created_at"`
	// Asset the fees were charged in.
	FeeAsset            *string `json:"fee_asset,omitempty"`
	FeePaid             Amount  `json:"fee_paid"`
	FilledQuantity      Amount  `json:"filled_quantity"`
	FilledQuoteQuantity Amount  `json:"filled_quote_quantity"`
	// Order id.
	ID                string      `json:"id"`
	Price             *Amount     `json:"price,omitempty"`
	Quantity          Amount      `json:"quantity"`
	QuoteQuantity     *Amount     `json:"quote_quantity,omitempty"`
	RemainingQuantity Amount      `json:"remaining_quantity"`
	ReservedRemaining Amount      `json:"reserved_remaining"`
	Side              OrderSide   `json:"side"`
	Status            OrderStatus `json:"status"`
	// Why the order was rejected or cancelled.
	StatusReason *string `json:"status_reason,omitempty"`
	StopPrice    *Amount `json:"stop_price,omitempty"`
	// Market symbol.
	Symbol           string            `json:"symbol"`
	TimeInForce      TimeInForce       `json:"time_in_force"`
	TriggerDirection *TriggerDirection `json:"trigger_direction,omitempty"`
	// When the trigger fired, if it has.
	TriggeredAt *time.Time `json:"triggered_at,omitempty"`
	Type        OrderType  `json:"type"`
	// When it last changed.
	UpdatedAt time.Time `json:"updated_at"`
}

// OrderSide: Which side of a market an order takes.
//
// The type is open: values added to the API later decode without error.
type OrderSide string

const (
	OrderSideBuy  OrderSide = "buy"
	OrderSideSell OrderSide = "sell"
)

// OrderStatus: Lifecycle of an order.
//
// The type is open: values added to the API later decode without error.
type OrderStatus string

const (
	OrderStatusPending         OrderStatus = "pending"
	OrderStatusOpen            OrderStatus = "open"
	OrderStatusPartiallyFilled OrderStatus = "partially_filled"
	OrderStatusFilled          OrderStatus = "filled"
	OrderStatusCancelled       OrderStatus = "cancelled"
	OrderStatusRejected        OrderStatus = "rejected"
	OrderStatusPendingTrigger  OrderStatus = "pending_trigger"
	OrderStatusExpired         OrderStatus = "expired"
)

// OrderType: Order types the matching engine accepts.
//
// The type is open: values added to the API later decode without error.
type OrderType string

const (
	OrderTypeLimit      OrderType = "limit"
	OrderTypeMarket     OrderType = "market"
	OrderTypeStopLimit  OrderType = "stop_limit"
	OrderTypeStopMarket OrderType = "stop_market"
)

// PasswordRules: Password constraints, published so a form can validate locally.
type PasswordRules struct {
	// Whether the password may contain the account's email address.
	AllowsEmailSubstring bool `json:"allows_email_substring"`
	// A short description of any further rules, for display beside the input.
	Description string `json:"description"`
	// Maximum length in characters.
	MaxLength int `json:"max_length"`
	// Minimum length in characters.
	MinLength int `json:"min_length"`
}

// PerpMarket: One listed perpetual market and its current figures.
type PerpMarket struct {
	// The provider's coin name, e.g. `BTC` or `kPEPE`.
	Coin        string `json:"coin"`
	FundingRate Amount `json:"funding_rate"`
	MarkPrice   Amount `json:"mark_price"`
	// The highest leverage allowed.
	MaxLeverage  int     `json:"max_leverage"`
	MidPrice     *Amount `json:"mid_price,omitempty"`
	OpenInterest Amount  `json:"open_interest"`
	OraclePrice  Amount  `json:"oracle_price"`
	Price24hAgo  Amount  `json:"price_24h_ago"`
	// Decimal places a size may have.
	SizeDecimals int    `json:"size_decimals"`
	Volume24h    Amount `json:"volume_24h"`
}

// PlaceOrderRequest: Places an order.
//
// Set `client_order_id` to make a retry safe: it is unique per account, so a repeat is refused before any funds move, and `GET /trading/orders/by-client-id/{client_order_id}` recovers the outcome. `Idempotency-Key` is not honoured for orders.
type PlaceOrderRequest struct {
	// Your own identifier. Unique per account.
	ClientOrderID *string   `json:"client_order_id,omitempty"`
	Price         *Amount   `json:"price,omitempty"`
	Quantity      *Amount   `json:"quantity,omitempty"`
	QuoteQuantity *Amount   `json:"quote_quantity,omitempty"`
	Side          OrderSide `json:"side"`
	StopPrice     *Amount   `json:"stop_price,omitempty"`
	// Market symbol.
	Symbol           string            `json:"symbol"`
	TimeInForce      *TimeInForce      `json:"time_in_force,omitempty"`
	TriggerDirection *TriggerDirection `json:"trigger_direction,omitempty"`
	Type             OrderType         `json:"type"`
}

// PlaceOrderResponse: The result of placing an order, including anything it executed immediately.
type PlaceOrderResponse struct {
	// Fills produced on entry, oldest first.
	Fills []Fill `json:"fills"`
	Order Order  `json:"order"`
}

// PoolID: Unique identifier of a liquidity pool.
//
// An alias of string: its format is not checked, so a future format keeps working.
type PoolID = string

// Pool: A pool as a client sees it.
//
// Reserves are the custody account's balances, so they include liquidity currently locked in resting orders. `price` is the curve's mid, which sits between the pool's own best bid and ask by exactly its fee — it is not a traded price.
type Pool struct {
	BaseReserve Amount `json:"base_reserve"`
	// When the pool was created.
	CreatedAt time.Time `json:"created_at"`
	// The pool's fee, in percent, priced into every quote it rests.
	FeePercent string `json:"fee_percent"`
	// Identifier.
	ID string `json:"id"`
	// Ladder steps per side.
	LadderSteps       int        `json:"ladder_steps"`
	Price             *Amount    `json:"price,omitempty"`
	QuoteReserve      Amount     `json:"quote_reserve"`
	SharesOutstanding Amount     `json:"shares_outstanding"`
	Status            PoolStatus `json:"status"`
	// Market the pool quotes.
	Symbol string `json:"symbol"`
}

// PoolStatus: Whether a pool quotes, and whether it accepts new liquidity.
//
// The type is open: values added to the API later decode without error.
type PoolStatus string

const (
	PoolStatusActive  PoolStatus = "active"
	PoolStatusPaused  PoolStatus = "paused"
	PoolStatusClosing PoolStatus = "closing"
)

// Position: One open position.
type Position struct {
	// Coin.
	Coin             string  `json:"coin"`
	EntryPrice       *Amount `json:"entry_price,omitempty"`
	FundingSinceOpen Amount  `json:"funding_since_open"`
	// Leverage.
	Leverage int `json:"leverage"`
	// `cross` or `isolated`.
	LeverageType     string  `json:"leverage_type"`
	LiquidationPrice *Amount `json:"liquidation_price,omitempty"`
	MarginUsed       Amount  `json:"margin_used"`
	PositionValue    Amount  `json:"position_value"`
	ReturnOnEquity   Amount  `json:"return_on_equity"`
	Size             Amount  `json:"size"`
	UnrealizedPnl    Amount  `json:"unrealized_pnl"`
}

// Positions: A margin summary and the open positions.
type Positions struct {
	AccountValue      Amount `json:"account_value"`
	MaintenanceMargin Amount `json:"maintenance_margin"`
	MarginUsed        Amount `json:"margin_used"`
	// The open positions.
	Positions     []Position `json:"positions"`
	TotalNotional Amount     `json:"total_notional"`
}

// FuturesPublicTrade: A public trade, with nothing that identifies the parties.
type FuturesPublicTrade struct {
	Price Amount `json:"price"`
	// `buy` or `sell`: the taker's side.
	Side string `json:"side"`
	Size Amount `json:"size"`
	// When, unix milliseconds.
	Time int64 `json:"time"`
}

// PublicTrade: A public trade.
//
// Deliberately anonymous: no account identifiers, and no indication of which side was the resting order beyond the aggressor direction.
type PublicTrade struct {
	// Trade id.
	ID       string `json:"id"`
	Price    Amount `json:"price"`
	Quantity Amount `json:"quantity"`
	// Gapless per-market sequence.
	Sequence int64     `json:"sequence"`
	Side     OrderSide `json:"side"`
	// When it executed.
	Timestamp time.Time `json:"timestamp"`
}

// ServerTime: The server's clock.
//
// Two-factor codes are time-based, so a client can compare its own clock against this before a skewed clock gets a correct code rejected.
type ServerTime struct {
	// Current time in milliseconds since the Unix epoch.
	EpochMs int64 `json:"epoch_ms"`
	// Current time as RFC 3339 with an explicit UTC offset.
	Iso string `json:"iso"`
}

// SortDirection: Sort direction for a paginated listing.
//
// The type is open: values added to the API later decode without error.
type SortDirection string

const (
	SortDirectionAsc  SortDirection = "asc"
	SortDirectionDesc SortDirection = "desc"
)

// SubAccount: A sub-account.
type SubAccount struct {
	// Always `false`. A sub-account has no withdrawal path — stated explicitly so a client does not have to infer it.
	CanWithdraw bool `json:"can_withdraw"`
	// When it was created.
	CreatedAt time.Time `json:"created_at"`
	// Opaque identifier. Use it to transfer funds and to issue API keys.
	ID string `json:"id"`
	// Whether it may trade.
	IsActive bool `json:"is_active"`
	// The label given at creation.
	Label string `json:"label"`
}

// TimeInForce: How long an order remains eligible to match.
//
// The type is open: values added to the API later decode without error.
type TimeInForce string

const (
	TimeInForceGtc      TimeInForce = "gtc"
	TimeInForceIoc      TimeInForce = "ioc"
	TimeInForceFok      TimeInForce = "fok"
	TimeInForcePostOnly TimeInForce = "post_only"
)

// TradeID: Unique identifier of a trade.
//
// An alias of string: its format is not checked, so a future format keeps working.
type TradeID = string

// TriggerDirection: Which way the price must move for a stop to fire.
//
// Explicit rather than inferred from the side, because the inference is ambiguous: a sell stop below the market is a stop-loss, and a sell stop above it is a take-profit. Both are legitimate, and guessing wrong means an order that fires at exactly the wrong moment — which is the one thing a protective order must never do.
//
// The type is open: values added to the API later decode without error.
type TriggerDirection string

const (
	TriggerDirectionAbove TriggerDirection = "above"
	TriggerDirectionBelow TriggerDirection = "below"
)

// UserID: Unique identifier of a user account.
//
// An alias of string: its format is not checked, so a future format keeps working.
type UserID = string

// WithdrawalAddress: A saved withdrawal address.
type WithdrawalAddress struct {
	// The address.
	Address string `json:"address"`
	// Asset, when restricted to one.
	Asset *string `json:"asset,omitempty"`
	// When it was saved.
	CreatedAt time.Time `json:"created_at"`
	// Address-book entry id.
	ID string `json:"id"`
	// Your label.
	Label string `json:"label"`
	// When it was last withdrawn to.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// Memo, if any.
	Memo *string `json:"memo,omitempty"`
	// Network code.
	Network string `json:"network"`
	// Whether ownership has been confirmed.
	Verified bool `json:"verified"`
}

// WithdrawalHistoryEntry: One transition in a withdrawal's life.
type WithdrawalHistoryEntry struct {
	// When.
	At time.Time `json:"at"`
	// Why, where a reason applies.
	Reason *string          `json:"reason,omitempty"`
	Status WithdrawalStatus `json:"status"`
}

// WithdrawalID: Unique identifier of a withdrawal.
//
// An alias of string: its format is not checked, so a future format keeps working.
type WithdrawalID = string

// Withdrawal: A withdrawal.
type Withdrawal struct {
	// Destination.
	Address string `json:"address"`
	Amount  Amount `json:"amount"`
	// Asset symbol.
	Asset string `json:"asset"`
	// When it was broadcast.
	BroadcastAt *time.Time `json:"broadcast_at,omitempty"`
	// Whether the account holder may still cancel it.
	Cancellable bool `json:"cancellable"`
	// When it confirmed to the required depth.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// Confirmations observed.
	Confirmations int `json:"confirmations"`
	// When it was requested.
	CreatedAt time.Time `json:"created_at"`
	// Explorer link, when available.
	ExplorerURL *string `json:"explorer_url,omitempty"`
	Fee         Amount  `json:"fee"`
	// Asset the fee was charged in.
	FeeAsset string `json:"fee_asset"`
	// Transitions this withdrawal has been through.
	History []WithdrawalHistoryEntry `json:"history"`
	// Withdrawal id.
	ID string `json:"id"`
	// Memo, if any.
	Memo *string `json:"memo,omitempty"`
	// Network code.
	Network string           `json:"network"`
	Status  WithdrawalStatus `json:"status"`
	// Transaction hash, once broadcast.
	Txid *string `json:"txid,omitempty"`
}

// WithdrawalStatus: Lifecycle of an outgoing withdrawal.
//
// `pending_approval` waits for an operator to approve the withdrawal. `broadcast_unknown`
// means the transaction may have been sent: the funds stay debited until it is resolved
// against the chain.
//
// The type is open: values added to the API later decode without error.
type WithdrawalStatus string

const (
	WithdrawalStatusRequested        WithdrawalStatus = "requested"
	WithdrawalStatusPendingApproval  WithdrawalStatus = "pending_approval"
	WithdrawalStatusApproved         WithdrawalStatus = "approved"
	WithdrawalStatusProcessing       WithdrawalStatus = "processing"
	WithdrawalStatusBroadcast        WithdrawalStatus = "broadcast"
	WithdrawalStatusCompleted        WithdrawalStatus = "completed"
	WithdrawalStatusRejected         WithdrawalStatus = "rejected"
	WithdrawalStatusCancelled        WithdrawalStatus = "cancelled"
	WithdrawalStatusFailed           WithdrawalStatus = "failed"
	WithdrawalStatusBroadcastUnknown WithdrawalStatus = "broadcast_unknown"
	WithdrawalStatusReverted         WithdrawalStatus = "reverted"
)
