// Code generated by tools/generate.py from cexy-api-spec; DO NOT EDIT.

package cexy

import (
	"net/url"
	"strconv"
	"time"
)

// SpecVersion is the info.version of the openapi.sdk.json this SDK was generated from.
const SpecVersion = "1.0.0"

// OperationID names one operation of the SDK surface.
type OperationID string

const (
	OpCancelAll               OperationID = "cancel_all"
	OpCancelOrder             OperationID = "cancel_order"
	OpDepositAddress          OperationID = "deposit_address"
	OpExchangeConfig          OperationID = "exchange_config"
	OpExitPool                OperationID = "exit_pool"
	OpExportDeposits          OperationID = "export_deposits"
	OpExportLedger            OperationID = "export_ledger"
	OpExportOrders            OperationID = "export_orders"
	OpExportTrades            OperationID = "export_trades"
	OpExportWithdrawals       OperationID = "export_withdrawals"
	OpGetAccountID            OperationID = "get_account_id"
	OpGetAsset                OperationID = "get_asset"
	OpGetBalance              OperationID = "get_balance"
	OpGetCandles              OperationID = "get_candles"
	OpGetDeposit              OperationID = "get_deposit"
	OpGetLedger               OperationID = "get_ledger"
	OpGetMarket               OperationID = "get_market"
	OpGetMarketTrades         OperationID = "get_market_trades"
	OpGetOrder                OperationID = "get_order"
	OpGetOrderBook            OperationID = "get_order_book"
	OpGetOrderByClientID      OperationID = "get_order_by_client_id"
	OpGetPool                 OperationID = "get_pool"
	OpGetWithdrawal           OperationID = "get_withdrawal"
	OpJoinPool                OperationID = "join_pool"
	OpListAPIKeys             OperationID = "list_api_keys"
	OpListAssets              OperationID = "list_assets"
	OpListBalances            OperationID = "list_balances"
	OpListDeposits            OperationID = "list_deposits"
	OpListFeeSchedules        OperationID = "list_fee_schedules"
	OpListMarkets             OperationID = "list_markets"
	OpListNetworks            OperationID = "list_networks"
	OpListNotifications       OperationID = "list_notifications"
	OpListOpenOrders          OperationID = "list_open_orders"
	OpListPools               OperationID = "list_pools"
	OpListSubAccounts         OperationID = "list_sub_accounts"
	OpListWithdrawalAddresses OperationID = "list_withdrawal_addresses"
	OpListWithdrawals         OperationID = "list_withdrawals"
	OpOrderHistory            OperationID = "order_history"
	OpPlaceOrder              OperationID = "place_order"
	OpServerTime              OperationID = "server_time"
	OpSubAccountBalances      OperationID = "sub_account_balances"
	OpTradeHistory            OperationID = "trade_history"
)

// operations is the SDK surface: exactly the operations in openapi.sdk.json.
var operations = map[OperationID]OperationInfo{
	OpCancelAll:               {Method: "POST", Path: "/api/v1/trading/orders/cancel-all", Auth: "api_key", Scope: "trade"},
	OpCancelOrder:             {Method: "DELETE", Path: "/api/v1/trading/orders/{order_id}", Auth: "api_key", Scope: "trade"},
	OpDepositAddress:          {Method: "GET", Path: "/api/v1/wallet/deposit-address", Auth: "api_key", Scope: "read"},
	OpExchangeConfig:          {Method: "GET", Path: "/api/v1/config", Auth: "none", Scope: ""},
	OpExitPool:                {Method: "POST", Path: "/api/v1/pools/{symbol}/exit", Auth: "api_key", Scope: "trade"},
	OpExportDeposits:          {Method: "GET", Path: "/api/v1/exports/deposits", Auth: "api_key", Scope: "read"},
	OpExportLedger:            {Method: "GET", Path: "/api/v1/exports/ledger", Auth: "api_key", Scope: "read"},
	OpExportOrders:            {Method: "GET", Path: "/api/v1/exports/orders", Auth: "api_key", Scope: "read"},
	OpExportTrades:            {Method: "GET", Path: "/api/v1/exports/trades", Auth: "api_key", Scope: "read"},
	OpExportWithdrawals:       {Method: "GET", Path: "/api/v1/exports/withdrawals", Auth: "api_key", Scope: "read"},
	OpGetAccountID:            {Method: "GET", Path: "/api/v1/account/id", Auth: "api_key", Scope: "read"},
	OpGetAsset:                {Method: "GET", Path: "/api/v1/assets/{symbol}", Auth: "none", Scope: ""},
	OpGetBalance:              {Method: "GET", Path: "/api/v1/account/balances/{asset}", Auth: "api_key", Scope: "read"},
	OpGetCandles:              {Method: "GET", Path: "/api/v1/markets/{symbol}/candles", Auth: "none", Scope: ""},
	OpGetDeposit:              {Method: "GET", Path: "/api/v1/wallet/deposits/{deposit_id}", Auth: "api_key", Scope: "read"},
	OpGetLedger:               {Method: "GET", Path: "/api/v1/account/ledger", Auth: "api_key", Scope: "read"},
	OpGetMarket:               {Method: "GET", Path: "/api/v1/markets/{symbol}", Auth: "none", Scope: ""},
	OpGetMarketTrades:         {Method: "GET", Path: "/api/v1/markets/{symbol}/trades", Auth: "none", Scope: ""},
	OpGetOrder:                {Method: "GET", Path: "/api/v1/trading/orders/{order_id}", Auth: "api_key", Scope: "read"},
	OpGetOrderBook:            {Method: "GET", Path: "/api/v1/markets/{symbol}/orderbook", Auth: "none", Scope: ""},
	OpGetOrderByClientID:      {Method: "GET", Path: "/api/v1/trading/orders/by-client-id/{client_order_id}", Auth: "api_key", Scope: "read"},
	OpGetPool:                 {Method: "GET", Path: "/api/v1/pools/{symbol}", Auth: "none", Scope: ""},
	OpGetWithdrawal:           {Method: "GET", Path: "/api/v1/wallet/withdrawals/{withdrawal_id}", Auth: "api_key", Scope: "read"},
	OpJoinPool:                {Method: "POST", Path: "/api/v1/pools/{symbol}/join", Auth: "api_key", Scope: "trade"},
	OpListAPIKeys:             {Method: "GET", Path: "/api/v1/account/api-keys", Auth: "api_key", Scope: "read"},
	OpListAssets:              {Method: "GET", Path: "/api/v1/assets", Auth: "none", Scope: ""},
	OpListBalances:            {Method: "GET", Path: "/api/v1/account/balances", Auth: "api_key", Scope: "read"},
	OpListDeposits:            {Method: "GET", Path: "/api/v1/wallet/deposits", Auth: "api_key", Scope: "read"},
	OpListFeeSchedules:        {Method: "GET", Path: "/api/v1/fees", Auth: "none", Scope: ""},
	OpListMarkets:             {Method: "GET", Path: "/api/v1/markets", Auth: "none", Scope: ""},
	OpListNetworks:            {Method: "GET", Path: "/api/v1/networks", Auth: "none", Scope: ""},
	OpListNotifications:       {Method: "GET", Path: "/api/v1/account/notifications", Auth: "api_key", Scope: "read"},
	OpListOpenOrders:          {Method: "GET", Path: "/api/v1/trading/orders", Auth: "api_key", Scope: "read"},
	OpListPools:               {Method: "GET", Path: "/api/v1/pools", Auth: "none", Scope: ""},
	OpListSubAccounts:         {Method: "GET", Path: "/api/v1/account/sub-accounts", Auth: "api_key", Scope: "read"},
	OpListWithdrawalAddresses: {Method: "GET", Path: "/api/v1/wallet/withdrawal-addresses", Auth: "api_key", Scope: "read"},
	OpListWithdrawals:         {Method: "GET", Path: "/api/v1/wallet/withdrawals", Auth: "api_key", Scope: "read"},
	OpOrderHistory:            {Method: "GET", Path: "/api/v1/trading/orders/history", Auth: "api_key", Scope: "read"},
	OpPlaceOrder:              {Method: "POST", Path: "/api/v1/trading/orders", Auth: "api_key", Scope: "trade"},
	OpServerTime:              {Method: "GET", Path: "/api/v1/time", Auth: "none", Scope: ""},
	OpSubAccountBalances:      {Method: "GET", Path: "/api/v1/account/sub-accounts/{id}/balances", Auth: "api_key", Scope: "read"},
	OpTradeHistory:            {Method: "GET", Path: "/api/v1/trading/trades", Auth: "api_key", Scope: "read"},
}

// ErrorCode is the machine-readable error.code of an API error. Branch on it, never on
// the message. The type is open: codes added to the API later arrive unchanged.
type ErrorCode string

// Every error code the API is known to return (errors.yaml).
const (
	CodeValidationFailed       ErrorCode = "VALIDATION_FAILED"
	CodeMalformedRequest       ErrorCode = "MALFORMED_REQUEST"
	CodeInvalidCursor          ErrorCode = "INVALID_CURSOR"
	CodePrecisionExceeded      ErrorCode = "PRECISION_EXCEEDED"
	CodeBelowMinimum           ErrorCode = "BELOW_MINIMUM"
	CodeAboveMaximum           ErrorCode = "ABOVE_MAXIMUM"
	CodeInvalidAddress         ErrorCode = "INVALID_ADDRESS"
	CodeMemoRequired           ErrorCode = "MEMO_REQUIRED"
	CodeUnauthenticated        ErrorCode = "UNAUTHENTICATED"
	CodeInvalidCredentials     ErrorCode = "INVALID_CREDENTIALS"
	CodeTokenExpired           ErrorCode = "TOKEN_EXPIRED"
	CodeSessionRevoked         ErrorCode = "SESSION_REVOKED"
	CodeTwoFactorRequired      ErrorCode = "TWO_FACTOR_REQUIRED"
	CodeTwoFactorInvalid       ErrorCode = "TWO_FACTOR_INVALID"
	CodeFreshTwoFactorRequired ErrorCode = "FRESH_TWO_FACTOR_REQUIRED"
	CodeForbidden              ErrorCode = "FORBIDDEN"
	CodeAPIKeyNotAllowed       ErrorCode = "API_KEY_NOT_ALLOWED"
	CodeFuturesRestricted      ErrorCode = "FUTURES_RESTRICTED"
	CodeAccountFrozen          ErrorCode = "ACCOUNT_FROZEN"
	CodeAccountOnHold          ErrorCode = "ACCOUNT_ON_HOLD"
	CodeEmailNotVerified       ErrorCode = "EMAIL_NOT_VERIFIED"
	CodeRegionBlocked          ErrorCode = "REGION_BLOCKED"
	CodeJurisdictionBlocked    ErrorCode = "JURISDICTION_BLOCKED"
	CodeNotFound               ErrorCode = "NOT_FOUND"
	CodeMethodNotAllowed       ErrorCode = "METHOD_NOT_ALLOWED"
	CodeAlreadyExists          ErrorCode = "ALREADY_EXISTS"
	CodeInvalidState           ErrorCode = "INVALID_STATE"
	CodeIdempotencyKeyConflict ErrorCode = "IDEMPOTENCY_KEY_CONFLICT"
	CodeWindowOpen             ErrorCode = "WINDOW_OPEN"
	CodeEvidenceContradicts    ErrorCode = "EVIDENCE_CONTRADICTS"
	CodeAmountMismatch         ErrorCode = "AMOUNT_MISMATCH"
	CodeConcurrentModification ErrorCode = "CONCURRENT_MODIFICATION"
	CodeInsufficientFunds      ErrorCode = "INSUFFICIENT_FUNDS"
	CodeInsufficientFeeFunds   ErrorCode = "INSUFFICIENT_FEE_FUNDS"
	CodeMarketUnavailable      ErrorCode = "MARKET_UNAVAILABLE"
	CodeDepositDisabled        ErrorCode = "DEPOSIT_DISABLED"
	CodeWithdrawalDisabled     ErrorCode = "WITHDRAWAL_DISABLED"
	CodeSelfTradeBlocked       ErrorCode = "SELF_TRADE_BLOCKED"
	CodeLimitExceeded          ErrorCode = "LIMIT_EXCEEDED"
	CodePriceUnavailable       ErrorCode = "PRICE_UNAVAILABLE"
	CodeRateLimited            ErrorCode = "RATE_LIMITED"
	CodeInternal               ErrorCode = "INTERNAL"
	CodeServiceUnavailable     ErrorCode = "SERVICE_UNAVAILABLE"
	CodeUnderMaintenance       ErrorCode = "UNDER_MAINTENANCE"
	CodeEngineOverloaded       ErrorCode = "ENGINE_OVERLOADED"
)

var knownErrorCodes = map[ErrorCode]bool{
	CodeValidationFailed:       true,
	CodeMalformedRequest:       true,
	CodeInvalidCursor:          true,
	CodePrecisionExceeded:      true,
	CodeBelowMinimum:           true,
	CodeAboveMaximum:           true,
	CodeInvalidAddress:         true,
	CodeMemoRequired:           true,
	CodeUnauthenticated:        true,
	CodeInvalidCredentials:     true,
	CodeTokenExpired:           true,
	CodeSessionRevoked:         true,
	CodeTwoFactorRequired:      true,
	CodeTwoFactorInvalid:       true,
	CodeFreshTwoFactorRequired: true,
	CodeForbidden:              true,
	CodeAPIKeyNotAllowed:       true,
	CodeFuturesRestricted:      true,
	CodeAccountFrozen:          true,
	CodeAccountOnHold:          true,
	CodeEmailNotVerified:       true,
	CodeRegionBlocked:          true,
	CodeJurisdictionBlocked:    true,
	CodeNotFound:               true,
	CodeMethodNotAllowed:       true,
	CodeAlreadyExists:          true,
	CodeInvalidState:           true,
	CodeIdempotencyKeyConflict: true,
	CodeWindowOpen:             true,
	CodeEvidenceContradicts:    true,
	CodeAmountMismatch:         true,
	CodeConcurrentModification: true,
	CodeInsufficientFunds:      true,
	CodeInsufficientFeeFunds:   true,
	CodeMarketUnavailable:      true,
	CodeDepositDisabled:        true,
	CodeWithdrawalDisabled:     true,
	CodeSelfTradeBlocked:       true,
	CodeLimitExceeded:          true,
	CodePriceUnavailable:       true,
	CodeRateLimited:            true,
	CodeInternal:               true,
	CodeServiceUnavailable:     true,
	CodeUnderMaintenance:       true,
	CodeEngineOverloaded:       true,
}

// DepositAddressParams holds the query parameters of deposit_address.
// Nil pointers are not sent.
type DepositAddressParams struct {
	// Asset symbol.
	//
	// Required.
	Asset string
	// Network code.
	//
	// Required.
	Network string
}

func (p *DepositAddressParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Asset != "" {
		v.Set("asset", p.Asset)
	}
	if p.Network != "" {
		v.Set("network", p.Network)
	}
	return v
}

// ExportParams holds the query parameters of export_deposits, export_ledger, export_orders, export_trades, export_withdrawals.
// Nil pointers are not sent.
type ExportParams struct {
	// Start of the period, inclusive. Defaults to 30 days ago.
	From *time.Time
	// End of the period, inclusive. Defaults to now.
	To *time.Time
}

func (p *ExportParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.From != nil {
		v.Set("from", p.From.UTC().Format(time.RFC3339Nano))
	}
	if p.To != nil {
		v.Set("to", p.To.UTC().Format(time.RFC3339Nano))
	}
	return v
}

// GetCandlesParams holds the query parameters of get_candles.
// Nil pointers are not sent.
type GetCandlesParams struct {
	// Bucket width.
	//
	// Required.
	Interval CandleInterval
	// Earliest bucket to return.
	StartTime *time.Time
	// Latest bucket to return.
	EndTime *time.Time
	// Maximum buckets. Capped server-side.
	Limit *int
}

func (p *GetCandlesParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Interval != "" {
		v.Set("interval", string(p.Interval))
	}
	if p.StartTime != nil {
		v.Set("start_time", p.StartTime.UTC().Format(time.RFC3339Nano))
	}
	if p.EndTime != nil {
		v.Set("end_time", p.EndTime.UTC().Format(time.RFC3339Nano))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	return v
}

// GetLedgerParams holds the query parameters of get_ledger.
// Nil pointers are not sent.
type GetLedgerParams struct {
	// Limit to one asset.
	Asset *string
	// Opaque cursor from a previous response's `next_cursor`. Omit for the first page.
	Cursor *string
	// Maximum items to return. Clamped to `MAX_LIMIT`.
	Limit *int
	// Sort direction. Defaults to newest-first.
	Direction *SortDirection
}

func (p *GetLedgerParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Asset != nil {
		v.Set("asset", *p.Asset)
	}
	if p.Cursor != nil {
		v.Set("cursor", *p.Cursor)
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.Direction != nil {
		v.Set("direction", string(*p.Direction))
	}
	return v
}

// GetMarketTradesParams holds the query parameters of get_market_trades.
// Nil pointers are not sent.
type GetMarketTradesParams struct {
	// Opaque cursor from a previous response's `next_cursor`. Omit for the first page.
	Cursor *string
	// Maximum items to return. Clamped to `MAX_LIMIT`.
	Limit *int
	// Sort direction. Defaults to newest-first.
	Direction *SortDirection
}

func (p *GetMarketTradesParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Cursor != nil {
		v.Set("cursor", *p.Cursor)
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.Direction != nil {
		v.Set("direction", string(*p.Direction))
	}
	return v
}

// GetOrderBookParams holds the query parameters of get_order_book.
// Nil pointers are not sent.
type GetOrderBookParams struct {
	// Price levels per side. Capped server-side.
	Depth *int
}

func (p *GetOrderBookParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Depth != nil {
		v.Set("depth", strconv.Itoa(*p.Depth))
	}
	return v
}

// ListDepositsParams holds the query parameters of list_deposits.
// Nil pointers are not sent.
type ListDepositsParams struct {
	// Limit to one asset.
	Asset *string
	// Opaque cursor from a previous response's `next_cursor`. Omit for the first page.
	Cursor *string
	// Maximum items to return. Clamped to `MAX_LIMIT`.
	Limit *int
	// Sort direction. Defaults to newest-first.
	Direction *SortDirection
}

func (p *ListDepositsParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Asset != nil {
		v.Set("asset", *p.Asset)
	}
	if p.Cursor != nil {
		v.Set("cursor", *p.Cursor)
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.Direction != nil {
		v.Set("direction", string(*p.Direction))
	}
	return v
}

// ListNotificationsParams holds the query parameters of list_notifications.
// Nil pointers are not sent.
type ListNotificationsParams struct {
	// Return only notices that have not been read.
	UnreadOnly *bool
	// Opaque cursor from a previous response's `next_cursor`. Omit for the first page.
	Cursor *string
	// Maximum items to return. Clamped to `MAX_LIMIT`.
	Limit *int
	// Sort direction. Defaults to newest-first.
	Direction *SortDirection
}

func (p *ListNotificationsParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.UnreadOnly != nil {
		v.Set("unread_only", strconv.FormatBool(*p.UnreadOnly))
	}
	if p.Cursor != nil {
		v.Set("cursor", *p.Cursor)
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.Direction != nil {
		v.Set("direction", string(*p.Direction))
	}
	return v
}

// ListOpenOrdersParams holds the query parameters of list_open_orders.
// Nil pointers are not sent.
type ListOpenOrdersParams struct {
	// Limit to one market.
	Symbol *string
	// Limit to one status.
	Status *OrderStatus
}

func (p *ListOpenOrdersParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Symbol != nil {
		v.Set("symbol", *p.Symbol)
	}
	if p.Status != nil {
		v.Set("status", string(*p.Status))
	}
	return v
}

// ListWithdrawalsParams holds the query parameters of list_withdrawals.
// Nil pointers are not sent.
type ListWithdrawalsParams struct {
	// Limit to one asset.
	Asset *string
	// Opaque cursor from a previous response's `next_cursor`. Omit for the first page.
	Cursor *string
	// Maximum items to return. Clamped to `MAX_LIMIT`.
	Limit *int
	// Sort direction. Defaults to newest-first.
	Direction *SortDirection
}

func (p *ListWithdrawalsParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Asset != nil {
		v.Set("asset", *p.Asset)
	}
	if p.Cursor != nil {
		v.Set("cursor", *p.Cursor)
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.Direction != nil {
		v.Set("direction", string(*p.Direction))
	}
	return v
}

// OrderHistoryParams holds the query parameters of order_history.
// Nil pointers are not sent.
type OrderHistoryParams struct {
	// Limit to one market.
	Symbol *string
	// Limit to one status.
	Status *OrderStatus
	// Opaque cursor from a previous response's `next_cursor`. Omit for the first page.
	Cursor *string
	// Maximum items to return. Clamped to `MAX_LIMIT`.
	Limit *int
	// Sort direction. Defaults to newest-first.
	Direction *SortDirection
}

func (p *OrderHistoryParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Symbol != nil {
		v.Set("symbol", *p.Symbol)
	}
	if p.Status != nil {
		v.Set("status", string(*p.Status))
	}
	if p.Cursor != nil {
		v.Set("cursor", *p.Cursor)
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.Direction != nil {
		v.Set("direction", string(*p.Direction))
	}
	return v
}

// TradeHistoryParams holds the query parameters of trade_history.
// Nil pointers are not sent.
type TradeHistoryParams struct {
	// Limit to one market.
	Symbol *string
	// Opaque cursor from a previous response's `next_cursor`. Omit for the first page.
	Cursor *string
	// Maximum items to return. Clamped to `MAX_LIMIT`.
	Limit *int
	// Sort direction. Defaults to newest-first.
	Direction *SortDirection
}

func (p *TradeHistoryParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Symbol != nil {
		v.Set("symbol", *p.Symbol)
	}
	if p.Cursor != nil {
		v.Set("cursor", *p.Cursor)
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.Direction != nil {
		v.Set("direction", string(*p.Direction))
	}
	return v
}
