#!/usr/bin/env python3
"""Generate the Go models and the operation table from the shared API spec.

    python3 tools/generate.py           # write models_gen.go and operations_gen.go
    python3 tools/generate.py --check   # exit 1 if the committed files are out of date

Inputs (from the cexy-api-spec repository, checked out next to this one, or $CEXY_API_SPEC):
  spec/openapi.sdk.json   models, operations, query parameters
  surface.yaml            the allowlist: auth and scope of every operation
  errors.yaml             every error code

Needs Python 3.9+ and PyYAML. The output is gofmt-clean; CI checks both.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SPEC_DIR = Path(os.environ.get("CEXY_API_SPEC", ROOT.parent / "cexy-api-spec"))
MODELS = ROOT / "models_gen.go"
OPERATIONS = ROOT / "operations_gen.go"
HEADER = "// Code generated by tools/generate.py from cexy-api-spec; DO NOT EDIT.\n\n"

# Schemas written by hand (errors.go) or not needed as Go types.
SKIP_SCHEMAS = {"ErrorBody", "ErrorResponse", "DetailValue", "ErrorCode", "Amount"}

# Go names for API schemas: "...Response" is dropped, except where the bare name is taken.
RENAMES = {
    "PlaceOrderResponse": "PlaceOrderResponse",
    "CancelAllResponse": "CancelAllResult",
    "JoinPoolResponse": "JoinPoolResult",
    "ExitPoolResponse": "ExitPoolResult",
    # Futures schemas whose bare names are taken by the spot models (CandleResponse -> Candle, ...).
    "Candle": "FuturesCandle",
    "Fill": "FuturesFill",
    "PublicTrade": "FuturesPublicTrade",
}

# Operations whose query parameters are identical share one params struct.
SHARED_PARAMS = {
    "export_deposits": "ExportParams",
    "export_ledger": "ExportParams",
    "export_orders": "ExportParams",
    "export_trades": "ExportParams",
    "export_withdrawals": "ExportParams",
}

INITIALISMS = {"id": "ID", "ids": "IDs", "url": "URL", "api": "API", "ip": "IP", "ips": "IPs",
               "uuid": "UUID", "json": "JSON", "http": "HTTP", "utc": "UTC", "tx": "Tx"}


def camel(name: str) -> str:
    parts = re.split(r"[_\-\s/]+", name)
    return "".join(INITIALISMS.get(p.lower(), p[:1].upper() + p[1:]) for p in parts if p)


def go_name(schema: str) -> str:
    if schema in RENAMES:
        return RENAMES[schema]
    if re.fullmatch(r"[A-Z][A-Za-z]*Id", schema):  # id aliases: OrderId -> OrderID
        return schema[:-2] + "ID"
    name = schema[: -len("Response")] if schema.endswith("Response") else schema
    return re.sub(r"^Api(?=[A-Z]|$)", "API", name)


def ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def comment(text: str | None, indent: str = "", name: str = "") -> str:
    if not text:
        return ""
    if name:
        text = f"{name}: {text.strip()}"
    lines = [ln.strip() for ln in text.strip().splitlines()]
    return "".join(f"{indent}//{(' ' + ln) if ln else ''}\n" for ln in lines)


class Gen:
    def __init__(self, spec: dict, surface: dict, error_codes: list[str]):
        self.spec = spec
        self.schemas = spec["components"]["schemas"]
        self.surface = surface
        self.error_codes = error_codes
        self.uses_time = False

    # -- types ---------------------------------------------------------------------------

    def is_struct(self, name: str) -> bool:
        s = self.schemas[name]
        return s.get("type") == "object" and "properties" in s

    def is_alias(self, name: str) -> bool:
        """A plain string schema without an enum (the id types): a Go alias of string."""
        s = self.schemas[name]
        return s.get("type") == "string" and "enum" not in s and "format" not in s

    def is_union(self, name: str) -> bool:
        s = self.schemas[name]
        return "oneOf" in s and (s.get("discriminator") or {}).get("propertyName") == "type"

    def base_type(self, s: dict) -> tuple[str, bool]:
        """Go type for a schema, and whether it may be a pointer (false for slices/maps/any)."""
        if "$ref" in s:
            name = ref_name(s["$ref"])
            if name == "Amount":
                return "Amount", True
            if name == "DetailValue":
                return "any", False
            return go_name(name), True  # structs, enums, id aliases and unions alike
        if "allOf" in s and len(s["allOf"]) == 1:
            return self.base_type(s["allOf"][0])
        t = s.get("type")
        if t == "string":
            if s.get("format") == "date-time":
                self.uses_time = True
                return "time.Time", True
            return "string", True
        if t == "integer":
            return ("int64" if s.get("format") == "int64" else "int"), True
        if t == "boolean":
            return "bool", True
        if t == "array":
            inner, _ = self.base_type(s["items"])
            return "[]" + inner, False
        if t == "object" and "additionalProperties" in s:
            inner, _ = self.base_type(s["additionalProperties"])
            return "map[string]" + inner, False
        if t == "object":
            return "map[string]any", False
        if t is None and not ({"oneOf", "anyOf", "enum"} & set(s)):
            return "json.RawMessage", False  # untyped in the spec: kept as raw JSON
        raise SystemExit(f"unsupported schema: {json.dumps(s)[:200]}")

    def field_type(self, s: dict, required: bool) -> tuple[str, bool]:
        """(Go type, omitempty)."""
        typ, pointable = self.base_type(s)
        optional = (not required) or s.get("nullable", False)
        if optional and pointable:
            return "*" + typ, True
        return typ, optional

    # -- models --------------------------------------------------------------------------

    def models(self) -> str:
        out: list[str] = []
        for name in sorted(self.schemas):
            if name in SKIP_SCHEMAS:
                continue
            s = self.schemas[name]
            gname = go_name(name)
            if "enum" in s:
                out.append(self.enum(gname, s))
            elif self.is_struct(name):
                out.append(self.struct(gname, s))
            elif self.is_alias(name):
                out.append(self.alias(gname, s))
            elif self.is_union(name):
                out.append(self.union(gname, s))
            else:
                raise SystemExit(f"schema {name} is neither an enum nor an object")
        body = "\n".join(out)
        imports = [pkg for pkg, used in (("encoding/json", "json.RawMessage" in body), ("time", self.uses_time)) if used]
        imports_src = "import (\n" + "".join(f'\t"{i}"\n' for i in imports) + ")\n\n" if imports else ""
        return HEADER + "package cexy\n\n" + imports_src + body

    def enum(self, gname: str, s: dict) -> str:
        doc = comment(s.get("description"), name=gname) or f"// {gname} is an API enum.\n"
        doc += "//\n// The type is open: values added to the API later decode without error.\n"
        lines = [doc + f"type {gname} string\n\n", "const (\n"]
        for v in s["enum"]:
            lines.append(f"\t{gname}{camel(str(v))} {gname} = {json.dumps(v)}\n")
        lines.append(")\n")
        return "".join(lines)

    def alias(self, gname: str, s: dict) -> str:
        doc = comment(s.get("description"), name=gname) or f"// {gname} is an API identifier.\n"
        doc += "//\n// An alias of string: its format is not checked, so a future format keeps working.\n"
        return doc + f"type {gname} = string\n"

    def union(self, gname: str, s: dict) -> str:
        """A oneOf told apart by "type": one struct with Type and a pointer per variant field,
        plus the raw JSON. Decoding never fails on an unknown type (Type keeps the value,
        Raw the object)."""
        variants = s["oneOf"]
        kinds: list[tuple[str, str]] = []
        fields: dict[str, tuple[dict, list[str]]] = {}
        for v in variants:
            kind = v["properties"]["type"]["enum"][0]
            kinds.append((kind, v.get("description") or ""))
            for prop, ps in v["properties"].items():
                if prop == "type":
                    continue
                if prop in fields and fields[prop][0] != ps:
                    raise SystemExit(f"{gname}.{prop} differs between variants")
                fields.setdefault(prop, (ps, []))[1].append(kind)
        tname = gname + "Type"
        doc = comment(s.get("description"), name=gname)
        doc += ("//\n// Type says which variant it is; only that variant's fields are set. A type added to\n"
                "// the API later decodes without error: Type holds it and Raw the whole object.\n")
        lines = [doc + f"type {gname} struct {{\n", f"\tType {tname} `json:\"type\"`\n"]
        for prop in sorted(fields):
            ps, used = fields[prop]
            typ, _ = self.base_type(ps)
            lines.append(comment((ps.get("description") or "").strip() + f"\n\nSet for type {', '.join(used)}.", "\t"))
            lines.append(f'\t{camel(prop)} *{typ} `json:"{prop},omitempty"`\n')
        lines.append("\t// Raw is the object as received (nil for values built in code).\n")
        lines.append("\tRaw json.RawMessage `json:\"-\"`\n}\n\n")
        lines.append(f"// {tname} tells the variants of {gname} apart. The type is open.\n"
                     f"type {tname} string\n\nconst (\n")
        for kind, d in kinds:
            lines.append(comment(d, "\t"))
            lines.append(f"\t{tname}{camel(kind)} {tname} = {json.dumps(kind)}\n")
        lines.append(")\n\n")
        lines.append(f"// Known reports whether Type is one this SDK version knows.\nfunc (r {gname}) Known() bool {{\n"
                     f"\tswitch r.Type {{\n\tcase {', '.join(tname + camel(k) for k, _ in kinds)}:\n"
                     "\t\treturn true\n\t}\n\treturn false\n}\n\n")
        lines.append(f"// UnmarshalJSON keeps the raw object and never fails on an unknown variant.\n"
                     f"func (r *{gname}) UnmarshalJSON(b []byte) error {{\n"
                     f"\ttype plain {gname}\n\tvar p plain\n"
                     "\tif err := json.Unmarshal(b, &p); err != nil {\n"
                     f"\t\t*r = {gname}{{Raw: append(json.RawMessage(nil), b...)}}\n\t\treturn nil\n\t}}\n"
                     f"\t*r = {gname}(p)\n\tr.Raw = append(json.RawMessage(nil), b...)\n\treturn nil\n}}\n")
        return "".join(lines)

    def struct(self, gname: str, s: dict) -> str:
        required = set(s.get("required", []))
        doc = comment(s.get("description"), name=gname) or f"// {gname} is an API object.\n"
        lines = [doc + f"type {gname} struct {{\n"]
        for prop in sorted(s["properties"]):
            ps = s["properties"][prop]
            typ, omit = self.field_type(ps, prop in required)
            lines.append(comment(ps.get("description"), "\t"))
            tag = prop + (",omitempty" if omit else "")
            lines.append(f'\t{camel(prop)} {typ} `json:"{tag}"`\n')
        lines.append("}\n")
        return "".join(lines)

    # -- operations ----------------------------------------------------------------------

    def operations(self) -> str:
        allowed = {(o["method"].upper(), o["path"]): o for o in self.surface["operations"]}
        ops = []
        for path, item in self.spec["paths"].items():
            for method, op in item.items():
                if method not in ("get", "post", "delete", "put", "patch"):
                    continue
                key = (method.upper(), path)
                if key not in allowed:
                    raise SystemExit(f"{method.upper()} {path} is in the spec but not in surface.yaml")
                ops.append((op["operationId"], method.upper(), path, allowed[key], op))
        missing = set(allowed) - {(m, p) for _, m, p, _, _ in ops}
        if missing:
            raise SystemExit(f"surface.yaml operations missing from the spec: {sorted(missing)}")
        ops.sort(key=lambda o: o[0])

        spec_codes = self.schemas["ErrorCode"]["enum"]
        if spec_codes != self.error_codes:
            raise SystemExit("errors.yaml and the spec's ErrorCode enum disagree; rebuild cexy-api-spec")

        self.uses_time = False
        out = [HEADER, "package cexy\n\n", "import (\n", '\t"net/url"\n', '\t"strconv"\n', '\t"time"\n', ")\n\n"]
        out.append(f"// SpecVersion is the info.version of the openapi.sdk.json this SDK was generated from.\n")
        out.append(f"const SpecVersion = {json.dumps(self.spec['info']['version'])}\n\n")

        out.append("// OperationID names one operation of the SDK surface.\ntype OperationID string\n\nconst (\n")
        for op_id, *_ in ops:
            out.append(f"\tOp{camel(op_id)} OperationID = {json.dumps(op_id)}\n")
        out.append(")\n\n")

        out.append("// operations is the SDK surface: exactly the operations in openapi.sdk.json.\n")
        out.append("var operations = map[OperationID]OperationInfo{\n")
        for op_id, method, path, allow, _ in ops:
            scope = allow.get("scope", "-")
            scope = "" if scope == "-" else scope
            out.append(f"\tOp{camel(op_id)}: {{Method: {json.dumps(method)}, Path: {json.dumps(path)}, "
                       f"Auth: {json.dumps(allow['auth'])}, Scope: {json.dumps(scope)}}},\n")
        out.append("}\n\n")

        out.append("// ErrorCode is the machine-readable error.code of an API error. Branch on it, never on\n"
                   "// the message. The type is open: codes added to the API later arrive unchanged.\n"
                   "type ErrorCode string\n\n// Every error code the API is known to return (errors.yaml).\nconst (\n")
        for code in self.error_codes:
            out.append(f"\tCode{camel(code.lower())} ErrorCode = {json.dumps(code)}\n")
        out.append(")\n\nvar knownErrorCodes = map[ErrorCode]bool{\n")
        for code in self.error_codes:
            out.append(f"\tCode{camel(code.lower())}: true,\n")
        out.append("}\n\n")

        written: set[str] = set()
        for op_id, _, _, _, op in ops:
            params = [p for p in op.get("parameters", []) if p["in"] == "query"]
            if not params:
                continue
            name = SHARED_PARAMS.get(op_id, camel(op_id) + "Params")
            if name in written:
                continue
            written.add(name)
            out.append(self.params(name, op_id, params))
        body = "".join(out)
        if "time." not in body.split(")\n\n", 1)[1]:
            body = body.replace('\t"time"\n', "")
        return body

    def params(self, name: str, op_id: str, params: list[dict]) -> str:
        users = sorted(k for k, v in SHARED_PARAMS.items() if v == name) or [op_id]
        lines = [f"// {name} holds the query parameters of {', '.join(users)}.\n"
                 "// Nil pointers are not sent.\n", f"type {name} struct {{\n"]
        enc = [f"func (p *{name}) values() url.Values {{\n\tv := url.Values{{}}\n\tif p == nil {{\n\t\treturn v\n\t}}\n"]
        for prm in params:
            s = prm["schema"]
            typ, _ = self.field_type(s, prm.get("required", False))
            field = camel(prm["name"])
            desc = prm.get("description") or s.get("description")
            if prm.get("required"):
                desc = ((desc or "").rstrip() + "\n\nRequired.").lstrip()
            lines.append(comment(desc, "\t"))
            lines.append(f"\t{field} {typ}\n")
            ptr = typ.startswith("*")
            base = typ.lstrip("*")
            val = f"*p.{field}" if ptr else f"p.{field}"
            if base == "time.Time":
                val = f"p.{field}"  # methods of time.Time work through the pointer
            conv = {
                "string": val,
                "int": f"strconv.Itoa({val})",
                "int64": f"strconv.FormatInt({val}, 10)",
                "bool": f"strconv.FormatBool({val})",
                "time.Time": f"{val}.UTC().Format(time.RFC3339Nano)",
            }.get(base, f"string({val})")
            if ptr:
                enc.append(f"\tif p.{field} != nil {{\n\t\tv.Set({json.dumps(prm['name'])}, {conv})\n\t}}\n")
            elif base == "string" or base not in ("int", "int64", "bool", "time.Time"):
                enc.append(f"\tif p.{field} != \"\" {{\n\t\tv.Set({json.dumps(prm['name'])}, {conv})\n\t}}\n")
            else:
                enc.append(f"\tv.Set({json.dumps(prm['name'])}, {conv})\n")
        lines.append("}\n\n")
        enc.append("\treturn v\n}\n\n")
        return "".join(lines) + "".join(enc)


def gofmt(src: str) -> str:
    gofmt_bin = os.environ.get("GOFMT", "gofmt")
    try:
        res = subprocess.run([gofmt_bin], input=src, capture_output=True, text=True)
    except FileNotFoundError:
        raise SystemExit(f"{gofmt_bin} not found: install Go, or set $GOFMT to the gofmt binary")
    if res.returncode != 0:
        raise SystemExit(f"gofmt failed:\n{res.stderr}")
    return res.stdout


def main() -> int:
    check = "--check" in sys.argv[1:]
    spec = json.loads((SPEC_DIR / "spec" / "openapi.sdk.json").read_text())
    surface = yaml.safe_load((SPEC_DIR / "surface.yaml").read_text())
    codes = yaml.safe_load((SPEC_DIR / "errors.yaml").read_text())["codes"]
    gen = Gen(spec, surface, codes)
    outputs = {MODELS: gofmt(gen.models()), OPERATIONS: gofmt(gen.operations())}
    stale = [p.name for p, src in outputs.items() if not p.exists() or p.read_text() != src]
    if check:
        if stale:
            print(f"out of date: {', '.join(stale)}; run python3 tools/generate.py", file=sys.stderr)
            return 1
        print("generated files are up to date")
        return 0
    for p, src in outputs.items():
        p.write_text(src)
    print(f"wrote {', '.join(p.name for p in outputs)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
